Brendan unit1 p1
alberttashu/study-algorithms pull request #3
Opened 2023-08-24 10:24 UTC by TheMightyYak1

used chatGPT to help a bit

2023-08-24 12:33 UTC, alberttashu approved these changes
Cool, we've started :)
Also been using ChatGPT to help out with the new language - it saves a lot of time

2023-08-24 12:45 UTC, alberttashu requested changes
Seems like you have only some .cs files. Could you please add the full project?
Or there's an issue with .gitignore for C# projects?

2023-08-25 02:10 UTC, TheMightyYak1 commented
should I have made an entire project? like a .NET project? I just made .cs files

2023-08-25 06:10 UTC, alberttashu approved these changes

2023-08-28 06:30 UTC, merged